# Generated by Django 3.1.3 on 2020-11-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_auto_20201107_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Plan XS', 'Plan XS'), ('Plan S', 'Plan S'), ('Plan L', 'Plan L'), ('Plan XL', 'Plan XL')], max_length=50, verbose_name='Nombre del Plan')),
                ('tipoPlan', models.CharField(choices=[('Plan Hogar', 'Plan Hogar'), ('Plan Movil', 'Plan Movil')], max_length=20, verbose_name='Tipo de Plan')),
                ('p_internet', models.BooleanField(default=False, verbose_name='¿Posee Internet?')),
                ('p_fibraOptica', models.BooleanField(default=False, verbose_name='¿Posee Fibra Optica')),
                ('p_tvCable', models.BooleanField(default=False, verbose_name='¿Posee TV Cable?')),
                ('p_canalesPremium', models.BooleanField(default=False, verbose_name='¿Posee Canales Premium')),
                ('p_telefoniaFija', models.BooleanField(default=False, verbose_name='¿Posee Telefonia Fija')),
                ('p_internetMovilIlimitado', models.BooleanField(default=False, verbose_name='¿Posee Internet Movil Ilimitado?')),
                ('p_minutosLibres', models.BooleanField(default=False, verbose_name='¿Posee Minutos Libres?')),
                ('p_redesSocialesGratis', models.BooleanField(default=False, verbose_name='¿Posee Redes Sociales Gratis?')),
                ('price', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='PlanHogar',
        ),
        migrations.DeleteModel(
            name='PlanMovil',
        ),
    ]
