# Generated by Django 3.1.3 on 2020-11-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_auto_20201107_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('Plan XS', 'Plan XS'), ('Plan S', 'Plan S'), ('Plan M', 'Plan M'), ('Plan L', 'Plan L'), ('Plan XL', 'Plan XL')], max_length=50, verbose_name='Nombre del Plan'),
        ),
    ]
